# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='pics_liked', to='time_display.User'),
        ),
        migrations.AddField(
            model_name='picture',
            name='uploaded_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pic', to='time_display.User'),
        ),
    ]
